### ISSUE TITLE
Complete initial ETL Script

### ISSUE THREAD

**Issue by david-garza** [david-garza/final_project#2]
Complete ETL script or scripts to perform ETL on the CSV files stored on the shared project GDrive.

Operations to consider:
- standardize column names
- verify data types match SQL data types
- convert dates to standard

**Comment by david-garza** [comment]
@BiancaTaisePommerening @lgrander 
- Bianca / Laura hand off database duties can remove Bianca off issues once handover is complete

Issues that still need to be addressed in ETL / tables in database
- Priority: 
1. make sure that beach attributes can join with water quality on beach_id
2. Make sure that water quality can join with weather station 1

Issues to resolve

1.  very all dates on tables are the same data type
2. drop snowfall from the weather station data after verifying if it has low data

**Comment by BiancaTaisePommerening** [comment]
@lgrander and @david-garza 

I have converted all the dates from object to datetime, as David mentioned that should be good for @david-garza and I to start the exploratory.

@laura I have pushed to github the final version of my ETL work, it is under the ETL branch. You can use the file now, just make sure you push it back to the same branch. I will be sharing with you via google drive the access to the AWS RDS endpoint, you should receive an email as well.

Step that still needs to be done:

- Drop snowfall from the weather station data after verifying if it has low data
- Do some more research on why how we could remove the time from the date column on the water_quality after its imported to pgAdmin.
- Take a look at all my code to try to understand how and what I did to connect our code to the database.
- Review the SQL module, specially the table join part.


If you have any questions, reach out to us.

**Comment by david-garza** [comment]
@BiancaTaisePommerening I am taking you off this issue, now that is has been handed to Laura.
